const theme = {
    light: {
        theme: 'light',
        bg: '#FFFFFF',
        txt: '#212121',
        inputtxt: '#9E9E9E',
        disable: '#757575',
        disable1: '#424242',
        disable2: '#616161',
        border: '#EEEEEE',
        borderbg: '#FFFFFF',
        btn: '#EEEDFE',
        btntxt: '#584CF4',
        input: '#FAFAFA',
        barstyle: 'dark-content',
        apple: require('../../assets/image/Apple.png'),
        location: require('../../assets/image/locationlight.png'),
        linebg: require('../../assets/image/Linebg.png'),
        direction: require('../../assets/image/direction.png'),
        elocation: require('../../assets/image/ELocation.png'),
        eticket: require('../../assets/image/eticket.png'),
        maplocation2: require('../../assets/image/maplocation2.png'),
        maplocation4: require('../../assets/image/maplocation4.png'),
        filter: require('../../assets/image/Filter2.png'),
        mastercard: require('../../assets/image/mastercard.png'),
        location2: require('../../assets/image/location.png'),
        face: require('../../assets/image/facereco.png'),
    },
    dark: {
        theme: 'dark',
        bg: '#212121',
        txt: '#FFFFFF',
        inputtxt: '#FFFFFF',
        disable: '#FFFFFF',
        disable1: '#E0E0E0',
        disable2: '#E0E0E0',
        border: '#35383F',
        borderbg: '#1F222A',
        btn: '#35383F',
        btntxt: '#FFFFFF',
        input: '#1F222A',
        barstyle: 'light-content',
        apple: require('../../assets/image/Apple1.png'),
        location: require('../../assets/image/locationdark.png'),
        linebg: require('../../assets/image/Linebgdark.png'),
        direction: require('../../assets/image/directiondark.png'),
        elocation: require('../../assets/image/ELocationdark.png'),
        eticket: require('../../assets/image/eticketdark.png'),
        maplocation2: require('../../assets/image/maplocation2dark.png'),
        maplocation4: require('../../assets/image/maplocation4dark.png'),
        filter: require('../../assets/image/Filter2dark.png'),
        mastercard: require('../../assets/image/mastercard1.png'),
        location2: require('../../assets/image/location2dark.png'),
        face: require('../../assets/image/facerecodark.png'),

    },

};

export default theme;